name: sporton
description: "SportOn - Modern CrossFit Timer App. Turn your workout ON!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Storage & Data
  shared_preferences: ^2.2.2

  # Audio
  audioplayers: ^5.2.1

  sqflite: ^2.3.0
  path: ^1.8.3

  # Social Features
  share_plus: ^7.2.2

  # System Integration
  wakelock_plus: ^1.2.5

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Flutter configuration
flutter:
  uses-material-design: true

  # Генерация локализации
  generate: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/fonts/

  fonts:
    # Шрифт для шапки главного меню
    - family: Gamestation
      fonts:
        - asset: assets/fonts/GamestationWarped.otf
          weight: 500

    # Основной шрифт для заголовков
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    # Шрифт для основного текста
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    # Специальный шрифт для таймера
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf